### ISSUE TITLE
A esp32 d1 mini is perfect

### ISSUE THREAD

**Issue by stofakiller** [igiannakas/mmwave-d1mini#1]
Hi, i tried a esp32 d1 mini, with 2 rows of pins on either side. and i can connect the sensor directly. pin 21/22 for rx/tx, 16/17 for the IO1 (not used) and IO2 from the sensor and vcc and gnd...
![esp32](https://user-images.githubusercontent.com/11716346/199714536-01c79a8f-f5ca-4482-9dae-432cd71d0327.PNG)

**Comment by Ramblurr** [comment]
@igiannakas Would you be willing to help scale the STL to fit the esp32 d1 mini? I'm not very talented with CAD unfortunately.

My calipers tell me that the ESP32 d1 mini PCB is 31.78 mm wide x 39.09mm long. If you measure the length from one end of the PCB to the other and include the micro usb socket then the length is about 39.9mm

**Comment by igiannakas** [comment]
> @igiannakas Would you be willing to help scale the STL to fit the esp32 d1 mini? I'm not very talented with CAD unfortunately.
> 
> My calipers tell me that the ESP32 d1 mini PCB is 31.78 mm wide x 39.09mm long. If you measure the length from one end of the PCB to the other and include the micro usb socket then the length is about 39.9mm

Should be able to scale it up to the size you want in your 3D printer slicer? No need for CAD to bump up its dimensions?

**Comment by nickelnine** [comment]
@stofakiller , did you happen to print a case to fit the ESP32 version?

**Comment by stofakiller** [comment]
Hi,Sorry not Venlig hilsen/Best Regards,Jan LarsenDen 20. jan. 2023 kl. 00.50 skrev nickelnine ***@***.***>:﻿
@stofakiller , did you happen to print a case to fit the ESP32 version?
