### ISSUE TITLE
not saving states

### ISSUE THREAD

**Issue by mortalone** [igiannakas/mmwave-d1mini#2]
hi.
i have installed your nice code.

but i cannot get it to save the states i select.

as an example. i try to select a distance of 5Meters. if i do this via home assistant, it is not registered on the esphome web portal. and the same thing if i set it in the esphome portal. it is not reansferred to homeassistant.

i do see the code being sent to the d1mini. but i dont know if it is set.

lso. if i set the distance in the portal. the state does not change. this goes for both distance, latency and sensitivity

**Comment by igiannakas** [comment]
Please try installing the first release (v1) and report back.

**Comment by mortalone** [comment]
well. it was a user error. i had not used the correct rx/tx ports. i had them switched arround.

**Comment by igiannakas** [comment]
No problem! Hope it works well for you :)
