### ISSUE TITLE
combine in one yaml

### ISSUE THREAD

**Issue by smic717394** [igiannakas/mmwave-d1mini#3]
First of all, thank you for the detailed post. The way it worked for me was creating a folder called mmwave in the esphome directory just to organise things, inside I copied the 2 folders header and packages. I had to modify the path in the yaml to the mmwave/packages/leapmmw_sensor.yml and then edited the sensor yaml and change the header path to mmwave/header/leapmmw_sensor.h, I guess I could just puth both header and sensor in one folder.

I have 2 questions, Would it be posible to combine the sensor and header in one yaml that flases into the mini d1, and second, in case this is not posible, say you have 3 units, do I need to create 3 folders with 3 sensor.h and sensor.yml files, o could I just redirect all to the same path?

**Comment by igiannakas** [comment]
They can all redirect to the same path - that is the reason why I split them out to multiple files. You only need one "sensor.yaml" per sensor. They can all be in the root directory, with the remaining items (.h / leapmmw_sensor.yml) reused.
