### ISSUE TITLE
Settings wont be saved

### ISSUE THREAD

**Issue by fwartner** [igiannakas/mmwave-d1mini#5]
I have a problem with saving the settings.
Once I reload the page, the settings I made are gone. Either in HA or the webinterface.

Running on the latest esphome version: 2022.12.7

**Comment by igiannakas** [comment]
Try waiting a few seconds between changing one setting and then changing another. The radar needs time to save each one individually.

**Comment by fwartner** [comment]
Doesn't have any effect.. :-/

**Comment by igiannakas** [comment]
It may be a wiring issue - can you post a screenshot from the complete HA device page? Are you seeing the sensor reporting back the preset distance and sensitivity values in home assistant?On 27 Jan 2023, at 08:53, Florian Wartner ***@***.***> wrote:﻿
Doesn't have any effect.. :-/

**Comment by fwartner** [comment]
![CleanShot 2023-01-27 at 10 02 20](https://user-images.githubusercontent.com/6692500/215048030-d13c7790-73f1-4d7b-8a19-252824d8867f.png)

Nothing really changed when I try to update anything. Like I said yesterday.. Once I reload the page, any setting is resettet.

**Comment by fwartner** [comment]
![CleanShot 2023-01-27 at 10 04 59](https://user-images.githubusercontent.com/6692500/215048754-6724fc33-a1f0-4c3b-a1ca-9b6a6da3fd8e.gif)

**Comment by igiannakas** [comment]
As you are not seeing the default values in the home assistant dashboard it is a connection error. Check that the wiring is done correctly - tx to rx and vice versa and that the motion detection pin is connected correctly.On 27 Jan 2023, at 09:06, Florian Wartner ***@***.***> wrote:﻿

**Comment by igiannakas** [comment]
This happens because serial communication is not established. This is usually due to a wiring issue or your pin out in the config is wrong.

**Comment by fwartner** [comment]
I was indeed the wiring ^^'

Thank you for the help you provided!
