### ISSUE TITLE
HA shows me always recognized

### ISSUE THREAD

**Issue by fwartner** [igiannakas/mmwave-d1mini#6]
![CleanShot 2023-01-26 at 12 28 10](https://user-images.githubusercontent.com/6692500/214824726-c7c41dff-9df2-41d5-ad0b-6acca87a026b.png)

It's actually useless..

**Comment by igiannakas** [comment]
Check if your radar is not picking up micro motions from a fan, air drafts, moving clothing etc. reduce sensitivity on the radar.

have been using them for the past 6 months and they have been reliable so the code is working, but the setup needs tweaking.

**Comment by fwartner** [comment]
Nah.. Doesn't work.. :-/

**Comment by ivishaltejwani** [comment]
> Check if your radar is not picking up micro motions from a fan, air drafts, moving clothing etc. reduce sensitivity on the radar.
> 
> have been using them for the past 6 months and they have been reliable so the code is working, but the setup needs tweaking.

any idea how to change sensitivity on arduino ide , example through blynk slider?
